name: Merhaba Dünya CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Elle tetikleme desteği

jobs:
  self_hosted_job:
    name: Merhaba Dünya (Self-hosted)
    runs-on: self-hosted

    steps:
      - name: Dosya oluştur
        run: echo "Bu dosya self-hosted runner tarafından oluşturuldu" > output.txt

      - name: Artifakt olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: mesaj-dosyasi
          path: output.txt

  enocsi:
    name: Run Enocsi Container Analyzer
    runs-on: self-hosted
    needs: github_hosted_job
    container:
      image: golang:1.24.5

    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}
      CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
    steps:

      - name: Set ENVIRONMENT based on branch
        run: |
          if [[ "${GITHUB_REF##*/}" == "master" ]]; then
            echo "ENVIRONMENT=Production" >> $GITHUB_ENV
            echo $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          fi


      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Container Analyzer
        run: |
          wget -q https://github.com/enocsi/cli/releases/download/ForCli/container-analyzer
          chmod +x container-analyzer

      - name: Run Analyzer
        run: |
          ./container-analyzer -i "paketobuildpacks/build"

  github_hosted_job:
    name: Dosyayı Kullan (GitHub Hosted)
    runs-on: ubuntu-latest
    needs: self_hosted_job

    steps:
      - name: Artifaktı indir
        uses: actions/download-artifact@v4
        with:
          name: mesaj-dosyasi

      - name: Dosya içeriğini oku
        run: cat output.txt
